before_script:
  # load the requested modules on oberon
  - module load anaconda/3 

tdev2-build:
  stage: build
  script:
    # create a Python virtual environment dedicated to the test (if not existing)
    - conda env create --file environment.yml 2> /dev/null || true
    - conda activate TDE

    # install tdev2
    #- pip install coverage intervaltree ipdb numpy pandas editdistance pytest
    - python setup.py build
    - python setup.py install

tdev2-test:
  stage: test
  script:
    # run the unit tests within the CI environment
    - conda activate TDE
      #- python setup.py test
    - pytest
